config/routes.rb
ChallengeTopical::Application.routes.draw do
  resources :topics, only: [:index, :show, :new, :create]
  root "topics#index"

  get '/login', to: 'users#login'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic, inverse_of: :comments, touch: true
  belongs_to :created_by_user, class_name: 'User', inverse_of: :comments

  validates :topic, presence: true
  validates :created_by_user, presence: true
  validates :comment, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :created_by_user, class_name: 'User', inverse_of: :topics

  has_many :comments, inverse_of: :topic

  validates :name, presence: true
  validates :content, presence: true
  validates :created_by_user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :topics, inverse_of: :created_by_user
  has_many :comments, inverse_of: :created_by_user

  validates :username, presence: true
  # Password presence validation is provided by ActiveModel::SecurePassword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  prepend_before_filter do
    session[:user_id] ||= User.first.id
  end

  def current_user
    User.find(session[:user_id])
  end
  helper_method(:current_user)
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.includes(:created_by_user)
  end

  def new
    @topic = Topic.new()
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save()
      redirect_to(@topic)
    else
      render('new')
    end
  end

  def show
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    session[:user_id] = params[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Topical</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-inner">
        <a class="brand" href="/">Topical</a>

        <div class="pull-right">
          <% User.all.each do |user| %>
            <%= link_to(user.username, login_path(user_id: user.id)) %>
          <% end %>
        </div>
      </div>
    </div>
  
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/_topic.html.erb
<%= cache topic do %>
  <tr>
    <td><%= link_to(topic.name, topic) %></td>
    <td colspan="2"><%= topic.created_by_user.username %></td>
  </tr>
<% end %>

app/views/topics/index.html.erb
<div class="row">
  <div class="span12">
    <h1 class="title">Topics</h1>

    <table class="table table-striped table-condensed table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th style="width: 100px;">Created By</th>
          <th style="width: 100px;"><%= link_to('New Topic', new_topic_path(), class: 'btn btn-primary pull-right') %></th>
        </tr>
      </thead>

      <tbody>
        <%= render @topics %>
      </tbody>
    </table>
  </div>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="span12">
    <h1 class="title">Create a new topic</h1>

    <%= form_for(@topic, html: { class: 'form-horizontal'} ) do |builder| %>
      <% if @topic.errors.any? %>
        <div class="alert alert-error">
          <h4>There were some errors. Please correct them and try again</h4>
          <ul>
            <% @topic.errors.full_messages.each do |message| %>
              <li><%=message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group">
        <label class="control-label" for="topic[name]">Topic Name:</label>
        <div class="controls">
          <%= builder.text_field(:name) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="topic[content]">Content</label>
        <div class="controls">
          <%= builder.text_area(:content, rows: 5) %>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= builder.submit(class: 'btn btn-primary') %>
        </div>
      </div>
    <% end %>
  </div>
</div>